### ISSUE TITLE
Traceback for write_model_to_disk.py

### ISSUE THREAD

**Issue by Raikster** [yossigor/AcousticKeylogger#30]
Hello,
I have problems generating a model. So what I did was the following:
Replace `from sklearn.externals import joblib` with `import joblib` to run it with the actual sklearn library.

When I try to run python3 `write_model_to_disk.py --training_folder <trainig folder path> --output <model output path>` with my training and output folders specified, I get the following traceback:
````
Traceback (most recent call last):
  File "write_model_to_disk.py", line 18, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "write_model_to_disk.py", line 13, in main
    acoustic_keylogger = AcousticKeylogger()
TypeError: __init__() missing 1 required positional argument: 'config'
````

What type of config is requested here?

Thank you

**Comment by yossigor** [comment]
Hi, did you manage to get this to work?
I wasn't available to maintain this project in a while.
